home/urls.py
from django.urls import path 

from home import views 

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'), 
    path('contact-us/', views.contact_us, name='contact_us'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')), 
    path('', include('user.urls')), 
    path('service/', include('service.urls')), 
]

service/urls.py
from django.urls import path 

from service import views 

app_name = 'service'

urlpatterns = [
    path('transfer/', views.TransferPage.as_view(), name='transfer'), 
    path('extract/', views.ExtractAccountView.as_view(), name='extract'), 
    path('loan-simulate/', views.NotLoggedLoan, name='loan_simulate'), 

    path('finance_data/contains/', views.FinanceDataUserView.as_view(), name='finance_data_content'),
    path('finance_data/update/', views.FinanceDataUserUpdateView.as_view(), name='finance_data_update'), 

    path('loan/', views.LoanView.as_view(), name='loan'),  
    path('verify_loan/', views.loan, name='verify_loan'), 
    path('confirm_loan/', views.ConfirmLoanView.as_view(), name='confirm_loan'), 

    path('deposit/', views.DepositView.as_view(), name='deposit'), 
]

home/models.py
from django.db import models

# Create your models here.
class ContactHome(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    message = models.TextField()

    

home/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms 
from django.core.exceptions import ValidationError

import re

from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList 

from home.models import ContactHome

EMAIL_REGEX = r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"

class ContactForm(forms.ModelForm):

    def __init__(self, *args, **kwargs) -> None:
        super(ContactForm, self).__init__(*args, **kwargs)

        self.fields['name'].label_suffix = ""
        self.fields['email'].label_suffix = ""
        self.fields['message'].label_suffix = ""

    class Meta:
        model = ContactHome 
        fields =  ("name", "email", "message")
        labels = {
            "name": "Nome", 
            "email": "Email", 
            "message": "Mensagem", 
        }
        
        widgets= {
            'name': forms.TextInput(attrs={
                'class': 'form-control', 
                'id': 'txtNome', 
                'placeholder': " ", 
            }), 
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'id': 'txtEmail', 
                'placeholder': " ", 
            }
            ), 
            'message': forms.Textarea(attrs={
                'class': 'form-control', 
                'id': 'txtmensagem', 
                'cols': "30", 
                'rows': '10', 
                'placeholder': ' ',
                'style':  "height:200px", 
            })

        }
    
    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email and not re.match(EMAIL_REGEX, email):
            self.add_error(
                'name', 
                ValidationError(
                    'Email inválido', 
                    code='invalid', 
                ), 
            )
        
        return email 

home/views.py
from django.shortcuts import render, redirect

from home.forms import ContactForm
# Create your views here.
def home(request):
    if request.user.is_authenticated: 
        return redirect('user:home')
    
    return render(request, 'homepage.html')

def contact_us(request):

    if request.method == "POST":
        form = ContactForm(request.POST)

        if form.is_valid():
            name = request.POST['name']
            
            form.save()

            return render(request, 'contact_confirm.html', {'name': name})
        
        print(form.errors)
        return render(request, 'contact.html', {'form': form})
    
    form = ContactForm()

    context = {
        "form": form, 
    }

    return render(request, 'contact.html', context)

home/templates/contact.html
{% extends "global/base.html" %}

{% block content %}

<main style="margin-top: 30px;">
    <div class="container">
        <div class="row justify-content-center">
            <form action="" class="col-sm-10 col-md-8 col-lg-6" method="POST">
                {% csrf_token %}

                {{ form.non_field_errors }}
                <h1 class="mb-3">Escreva sua mensagem</h1>

                {% for field in form %}
                <div class="form-floating mb-3">
                    {{field}}
                    <label for={{field.id}}>
                        {{field.label_tag}}
                    </label>
                    {{field.errors}}
                </div>
                {% endfor %}

                <button class="btn btn-lg btn-dark" type="submit">
                    Enviar Mensagem
                </button>


                <p class="mt-5">
                    Faremos nosso melhor para responder sua mensagem em até 48 horas.
                </p>
                <p class="mt-3">
                    Atenciosamente, <br>
                    Central de Relacionamento MockBank.
                </p>
            </form>
        </div>
    </div>
</main>
{% endblock content %}

home/templates/contact_confirm.html
{% extends "global/base.html" %}

{% block content %}

<main style="margin-top: 30px;">
    <div class="container">
        <h1>Confirmação de contato</h1>
        <hr>
        <p>
            Olá <strong>{{name}}</strong>, 
        </p>
        
        <p>
            Obrigado por entrar em contato conosco, faremos o possível para retornar o contato em no máximo 48 horas.
        </p>
        
        <p>
            Cordialmente, 
            <br>
            Central de Relacionamento MockBank. 
        </p>
    
        <p>
            <a href={% url "home:home" %} class="btn btn-dark">
                Voltar à página principal 
            </a>
        </p>
    </div>
</main>
{% endblock content %}

home/templates/home.html
{% extends "global/base.html" %}
{% load static %}

{% block content %}
<div class="container  mt-4 content-section ">
    <div class="row align-items-center">
        <div class="col-12 col-md-6 text-center text-md-start ">
            <h1 class="display-4">Crédito rápido, <br>
                simples
            </h1>
        </div>
        <div class="col-md-5 d-none d-md-block text-end me-lg-4">
            <i class="bi bi-cash-coin text-dark" style="font-size: 100px;"></i>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-8 col-md-12 text-center text-md-start d-grid d-md-block btn-simulate ms-md-5">
            <a href="#" class="btn btn-dark btn-lg">Simular agora</a>
        </div>
    </div>
</div>
{% endblock content %}

home/templates/homepage.html
{% extends "global/base.html" %}
{% load static %}

{% block content %}
<div class="container  mt-4 content-section ">
    <div class="row align-items-center">
        <div class="col-12 col-md-6 text-center text-md-start ">
            <h1 class="display-4">Crédito rápido, <br>
                simples
            </h1>
        </div>
        <div class="col-md-5 d-none d-md-block text-end me-lg-4">
            <i class="bi bi-cash-coin text-dark" style="font-size: 100px;"></i>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-8 col-md-12 text-center text-md-start d-grid d-md-block btn-simulate ms-md-5">
            <a href={% url "service:loan_simulate" %} class="btn btn-dark btn-lg">Simular agora</a>
        </div>
    </div>
</div>
{% endblock content %}