home/urls.py
from django.urls import path 

from home import views 

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'), 
    path('contact-us/', views.contact_us, name='contact_us'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')), 
    path('', include('user.urls')), 
    path('service/', include('service.urls')), 
]

service/urls.py
from django.urls import path 

from service import views 

app_name = 'service'

urlpatterns = [
    path('transfer/', views.TransferPage.as_view(), name='transfer'), 
    path('extract/', views.ExtractAccountView.as_view(), name='extract'), 
    path('loan-simulate/', views.NotLoggedLoan, name='loan_simulate'), 

    path('finance_data/contains/', views.FinanceDataUserView.as_view(), name='finance_data_content'),
    path('finance_data/update/', views.FinanceDataUserUpdateView.as_view(), name='finance_data_update'), 

    path('loan/', views.LoanView.as_view(), name='loan'),  
    path('verify_loan/', views.loan, name='verify_loan'), 
    path('confirm_loan/', views.ConfirmLoanView.as_view(), name='confirm_loan'), 

    path('deposit/', views.DepositView.as_view(), name='deposit'), 
]

user/urls.py
from django.urls import path 

from user import views 

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),  

    path("home/", views.HomePageView.as_view(), name="home"),

    path('user/create/', views.CreateUser.as_view(), name='create'), 

    path('user/messages/', views.ListMessageUser.as_view(), name='list_messages'), 
    path('user/messages/new/', views.NewMessageView.as_view(), name='create_message'), 
    path('user/messages/<slug:message_id>/', views.MessageDetailView.as_view(), name='detail_message'),

    path('profile/', views.ProfileUser.as_view(), name='profile'), 
    
]

home/models.py
from django.db import models

# Create your models here.
class ContactHome(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    message = models.TextField()

    

user/models.py
from django.db import models
from django.contrib.auth.models import User as DjangoUser 

import uuid 

class FinanceDataUser(models.Model):
    dependents = models.IntegerField(blank=True, default=0)
    education = models.IntegerField(default=0)
    employed = models.IntegerField(default=0)
    annual_income = models.DecimalField(max_digits=8, decimal_places=2, default=float(0), blank=True)
    score = models.IntegerField(default=500)
    residential_assets = models.DecimalField(max_digits=8, decimal_places=2, default=float(0), blank=True)
    commercial_assets = models.DecimalField(max_digits=8, decimal_places=2, default=float(0), blank=True)
    luxury_assets = models.DecimalField(max_digits=8, decimal_places=2, default=float(0), blank=True)
    bank_assets = models.DecimalField(max_digits=8, decimal_places=2, default=float(0), blank=True)
    active = models.BooleanField(default=False)
class User(models.Model):
    user_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user_phone = models.CharField(max_length=30, blank=True)

    account_balance = models.DecimalField(max_digits=8, decimal_places=2, default=float(0))
    account_limit = models.DecimalField(max_digits=8, decimal_places=2, default=float(0))

    owner = models.OneToOneField(DjangoUser, on_delete=models.CASCADE)
    finance_data = models.OneToOneField(FinanceDataUser, on_delete=models.CASCADE, null=True)

class UserMessages(models.Model): 
    message_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    subject = models.CharField(max_length=100)
    message_content = models.TextField()
    
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    response_from = models.OneToOneField('self', on_delete=models.CASCADE, null=True)
    
    message_from = models.ForeignKey(DjangoUser, on_delete=models.CASCADE, related_name='message_from')
    message_to = models.ForeignKey(DjangoUser, on_delete=models.CASCADE, related_name='message_to')
    
    message_read = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.subject  
    
    class Meta: 
        ordering = ["-created_at"]

home/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms 
from django.core.exceptions import ValidationError

import re

from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList 

from home.models import ContactHome

EMAIL_REGEX = r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"

class ContactForm(forms.ModelForm):

    def __init__(self, *args, **kwargs) -> None:
        super(ContactForm, self).__init__(*args, **kwargs)

        self.fields['name'].label_suffix = ""
        self.fields['email'].label_suffix = ""
        self.fields['message'].label_suffix = ""

    class Meta:
        model = ContactHome 
        fields =  ("name", "email", "message")
        labels = {
            "name": "Nome", 
            "email": "Email", 
            "message": "Mensagem", 
        }
        
        widgets= {
            'name': forms.TextInput(attrs={
                'class': 'form-control', 
                'id': 'txtNome', 
                'placeholder': " ", 
            }), 
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'id': 'txtEmail', 
                'placeholder': " ", 
            }
            ), 
            'message': forms.Textarea(attrs={
                'class': 'form-control', 
                'id': 'txtmensagem', 
                'cols': "30", 
                'rows': '10', 
                'placeholder': ' ',
                'style':  "height:200px", 
            })

        }
    
    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email and not re.match(EMAIL_REGEX, email):
            self.add_error(
                'name', 
                ValidationError(
                    'Email inválido', 
                    code='invalid', 
                ), 
            )
        
        return email 

user/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList

from user.models import User as UserModel, UserMessages

class UserLoginForm(AuthenticationForm):
    def __init__(self,  *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'

class UserRegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self,).__init__(*args, **kwargs)

        self.label_suffix = ''
    class Meta:
        model = UserModel 
        fields = ('user_phone', )
        labels = {
            'user_phone': 'Telefone de contato', 
        }

        widgets = {
            'user_phone': forms.TextInput(attrs={
                'class': 'form-control', 
            }),
        }

class MemberRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(MemberRegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

        self.label_suffix = ''

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 
                  'email', 'password1', 'password2', )
        
        labels = {
            'username': 'Usuário', 
            'first_name': 'Nome', 
            'last_name': 'Sobrenome', 
            'email': 'Endereço de Email', 
            'password1': 'Senha', 
            'password2': 'Confirmação de senha', 
        }

        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control', 
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control', 
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control', 
            }), 
        }

class SentMessageForm(forms.ModelForm):
    user_to = forms.CharField(max_length=150, label='Enviar para', required=False,  widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'userInput'}))

    def __init__(self, *args, **kwargs): 
        from_user = kwargs.pop('from_user', None)

        super(SentMessageForm, self).__init__(*args, **kwargs)

        self.from_user = from_user 
        self.fields['user_to'].validators = []
    class Meta: 
        model = UserMessages
        fields = ('subject', 'message_content')

        labels = {
            'subject': 'Assunto', 
            'message_content': 'Mensagem', 
        }

        widgets = {
            'subject': forms.TextInput(attrs={
                'class': 'form-control', 
                'id': 'subjectInput', 
            }), 
            'message_content': forms.Textarea(attrs={
                'class': 'form-control', 
                'id': 'messageInput', 
            }), 
        }

    def clean_user_to(self): 
        username = self.cleaned_data['user_to']
        
        if username == '': 
            username = 'mockbank'

        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            raise ValidationError('O contato informado não existe ou é inválido.')

        return user
    
    def save(self, commit=True): 
        instance = super().save(commit=False)
        instance.message_to = self.cleaned_data['user_to']
        instance.message_from = self.from_user 

        if commit: 
            instance.save()
        
        return instance 

home/views.py
from django.shortcuts import render, redirect

from home.forms import ContactForm
# Create your views here.
def home(request):
    if request.user.is_authenticated: 
        return redirect('user:home')
    
    return render(request, 'homepage.html')

def contact_us(request):

    if request.method == "POST":
        form = ContactForm(request.POST)

        if form.is_valid():
            name = request.POST['name']
            
            form.save()

            return render(request, 'contact_confirm.html', {'name': name})
        
        print(form.errors)
        return render(request, 'contact.html', {'form': form})
    
    form = ContactForm()

    context = {
        "form": form, 
    }

    return render(request, 'contact.html', context)

user/views.py
from typing import Any

from django.shortcuts import render, redirect 
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User 
from django.views.generic.base import TemplateView, View
from django.views.generic import DetailView, ListView
from django.db.models import Q 

from user import forms 
from user.models import User as BaseUser, UserMessages, FinanceDataUser
from user.services import UserService

class LoginUser(View):
    def post(self, request): 
        form = forms.UserLoginForm(request, self.request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)

            UserService.verify_new_loan(user)

            return redirect('user:home')
        
        context = {
            'form': form, 
        }   

        return render(request, 'login.html', context)         

    def get(self, request): 
        context = {
            'form': forms.UserLoginForm()
        }

        return render(request, 'login.html', context)

@method_decorator(login_required(login_url='user:login'), name='dispatch')
class LogoutUser(View):
    def get(self, request):
        auth.logout(request)

        return redirect('home:home')

class CreateUser(View):
    def get(self, request): 
        context = {
            'user_form': forms.UserRegisterForm(), 
            'member_form': forms.MemberRegisterForm(), 
        }

        return render(request, 'create.html', context)
    
    def post(self, request): 
        user_form = forms.UserRegisterForm(self.request.POST)
        member_form = forms.MemberRegisterForm(self.request.POST)

        if user_form.is_valid() and member_form.is_valid():
            member = member_form.save()
            user = user_form.save(commit=False)

            finance = FinanceDataUser()
            finance.save()

            user.owner = member
            user.finance_data = finance 
            user.save()

            messages.success(request, f"Sua conta foi criada Sr(a) { member.first_name }, ficamos felizes em ter você aqui!")

            return redirect('user:login')
        context = {
            'user_form': user_form, 
            'member_form': member_form, 
        }    

        return render(request, 'create.html', context)
    
    

@method_decorator(login_required(login_url='user:login'), name='dispatch')
class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context['user'] = UserService.get_user_django(username=self.request.user.username)
        context['account'] = UserService.user_balance(self.request.user.id)

        return context  
        
@method_decorator(login_required(login_url='user:login'), name='dispatch')
class ProfileUser(View): 
    def get(self, request): 
        context = {
            'user': User.objects.get(username=self.request.user.username), 
            'base_user': UserService.get_user_app(self.request.user.id)
        }

        return render(request, 'profile_user.html', context)

@method_decorator(login_required(login_url='user:login'), name='dispatch')
class ListMessageUser(ListView): 
    model = UserMessages 
    template_name = 'list_messages.html'
    context_object_name = 'messages'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context['messages'] = UserMessages.objects.filter(Q(message_to = self.request.user) | Q(message_from = self.request.user))

        return context 
    
@method_decorator(login_required(login_url='user:login'), name='dispatch')
class MessageDetailView(DetailView): 
    model = UserMessages 
    template_name = 'detail_messages.html'
    context_object_name = 'message'
    slug_field = 'message_id'
    slug_url_kwarg = 'message_id'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        
        message = UserMessages.objects.get(message_id=self.kwargs['message_id'])

        if message.message_read is False: 
            message.message_read = True  
            
            message.save()

        context['message'] = message 

        return context 

@method_decorator(login_required(login_url='user:login'), name='dispatch')
class NewMessageView(View): 
    def get(self, request): 
        context = { 
            'form': forms.SentMessageForm()
        }

        return render(request, 'new_message_user.html', context)
    
    def post(self, request): 
        form = forms.SentMessageForm(request.POST, from_user=request.user)

        if form.is_valid(): 
            form.save()

            return redirect('user:list_messages')

        context = {
            'form': forms.SentMessageForm(request.POST, from_user=request.user)
        }

        return render(request, 'new_message_user.html', context)

user/templates/create.html
{% extends "global/base.html" %}

{% block content %}

<main style="margin-top: 30px;">
    <div class="container mb-5">
        <h2 class="mb-3 text-center">Criar minha conta MockBank</h2>
        <div class="row justify-content-center">
            <form action="" class="col-sm-10 col-md-8 col-lg-6" method="POST">
                {% csrf_token %}

                {{ user_form.non_field_errors }}
                {{ member_form.non_field_errors }}

                
                <p class="lead"> Dados de Usuário </p>
                {% for field in member_form %}

                <div class="mb-3">
                    {{field.errors}}
                </div>
                
                <div class="form-floating mb-4">
                    {{field}}
                    <label for={{field.id}}>
                        {{field.label_tag}}
                    </label>
                    <div class="list-unstyled mt-2 ms-1 fs-6">
                        {{field.help_text }}    
                    </div>
                    
                    
                </div>
                {% endfor %}

                <hr>
                <p class="lead"> Dados de Contato </p>
                {% for field in user_form %}
                <div class="form-floating mb-3">
                    {{field.errors}}
                    {{field}}
                    <label for={{field.id}}>
                        {{field.label_tag}}
                    </label>
                </div>
                {% endfor %}

                <button class="btn btn-lg btn-dark" type="submit">
                    Criar conta
                </button>      
            </form>
        </div>
    </div>
</main>
{% endblock content %}

user/templates/detail_messages.html
{% extends "global/base.html" %}

{% block content %}
<main>
    <div class="container mt-5">
        <div class="row">
            <div class="col-12 col-lg-2 text-end mt-3 mb-3 mb-lg-0" >
                <a href="#" class="btn btn-dark" style="width: 190px;">
                    Responder Mensagem
                </a>
                <a href= {% url "user:list_messages" %} class="btn btn-dark  mt-2" style="width: 190px;">
                    Voltar
                </a>
            </div>
            <div class="col-12 col-lg-10 border rounded">
                <div class="col-12 mt-2 mb-2 pt-3 ps-3 pe-3">
                    <h2>{{ message.subject }}</h2>
                    <hr>
                    <p class="lead ms-2"> {{ message.message_content }}</p>
                    
                    <p class="d-block text-end">
                        {% if message.message_from == user %}
                        Enviado para <strong>{{ message.message_to }}</strong> em 
                        {% else %}
                        Recebido de <strong>{{ message.message_from }}</strong> em 
                        {% endif %}
                        {{ message.created_at }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</main> 

{% endblock content %}

user/templates/home.html
{% extends "global/base.html" %}

{% load static %}
{% load humanize %}

{% block content %}
<main>
    <section class="container mt-5 mb-5">
        {% if messages %}
        {% for message in messages %}
        <div class= {% if message.tags == 'error' %}"alert alert-danger col-8 text-start mt-5"{% else %} "alert alert-success col-8 text-start mt-5"{% endif %}role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="col-12 col-md-10 col-lg-8 mx-auto">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-2">
                            <img src={% static "img/mockbank_logo_minimal.png" %} width="100px" alt="" class="">
                        </div>
                    </div>

                    <div class="row mt-5">
                        <div class="col-12 justify-content-between d-flex">
                            <p class="lead">Saldo em conta</p>
                            {% if account.balance < 0 %} 
                                <p class="lead text-danger">R$ {{ account.balance }}</p>
                            {% else %}
                                <p class="lead text-dark">R$ {{ account.balance }}</p>
                            {% endif %}

                        </div>
                        <hr class="my-2">
                        <div class="col-12 mt-3">
                            <a class="link-underline-opacity-0 link-underline-opacity-0-hover link-dark d-block col-12 fs-5"
                                href= {% url "service:extract" %}>
                                Conferir Extrato <i class="bi bi-arrow-right-short float-end fs-2 mt-0"></i>
                            </a>

                            <div class="col-12 mt-5 d-flex justify-content-between p-3 rounded-3">
                                {% if account.limit == 0 %}
                                <p class="d-inline-block my-auto">Você não possui limite especial no momento.</p>
                                {% else %}
                                <p class="d-inline-block my-auto">Limite especial da conta </p>

                                <p class="d-inline-block my-auto ">R$ {{ account.limit }}</p>
                                {% endif %}
                            </div>
                            {% if account.used_limit > 0 %}
                            <p class="mt-4">Você está utilizando <strong>R$ {{ account.used_limit }} </strong> do seu limite da
                                conta.</p>
                            {% else %}

                            {% endif %}
                            
                        </div>

                    </div>
                </div>
            </div>

            <div class="row justify-content-between mt-5">
                <div class="col-4">

                    <a href={% url "service:finance_data_content" %}
                        class="card justify-content-center text-center link-underline-opacity-0 link-underline-opacity-0-hover link-dark"
                        style="height: 100px;">
                        <i class="bi bi-cash-coin fs-5"></i>
                        Empréstimo
                    </a>
                </div>
                <div class="col-4">
                    <a href={% url "service:deposit" %}
                        class="card justify-content-center text-center link-underline-opacity-0 link-underline-opacity-0-hover link-dark"
                        style="height: 100px;">
                        <i class="bi bi-piggy-bank-fill fs-5"></i>
                        Depósito
                    </a>
                </div>
                <div class="col-4">

                    <a href={% url "service:transfer" %}
                        class="card justify-content-center text-center link-underline-opacity-0 link-underline-opacity-0-hover link-dark"
                        style="height: 100px;">
                        <i class="bi bi-arrow-bar-right fs-5"></i>
                        Transferência
                    </a>
                </div>
            </div>

            <hr class="my-5">

            <div class="row">
                <div class="col-12">
                    <button class="btn btn-dark w-100 text-start p-3">
                        <i class="bi bi-bag-check-fill fs-4 ms-1 me-1 "></i>
                        <p class="d-inline">Benefícios MockBank</p>

                    </button>
                </div>

            </div>
        </div>
    </section>
</main>
{% endblock content %}

user/templates/list_messages.html
{% extends "global/base.html" %}

{% block content %}

<main>
    <div class="container mt-5">
        <div class="row">
            <div class="col-12 col-lg-2 text-end mt-3 mb-3 mb-lg-0">
                <a href={% url "user:create_message" %} class="btn btn-dark" style="width: 190px;">
                    Nova Mensagem
                </a>
                <a href={% url "user:home" %} class="btn btn-dark mt-2" style="width: 190px;">
                    Página Inicial
                </a>
            </div>
            <div class="col-12 col-lg-10 border-start">
                <div class="col-12 mt-2 mb-3">
                    {% if messages %}
                    {% for content in messages %}
                    <a href={% url "user:detail_message" message_id=content.message_id %} class="border rounded d-block p-2 link-underline-opacity-0 link-underline mb-3">
                        <div class="row">
                            <div class="col-10">
                                
                                <p class="text-dark">
                                    {% if content.message_from == user %}
                                    <strong>Enviada em</strong> 
                                    {% else %}
                                    <strong>Recebida em</strong> 
                                    {% endif %}    
                                    {{ content.created_at }}
                                </p>
                                <p class="lead text-dark"> {{ content.subject }} </p>
                            </div>
                            <div class="col-lg-2 border-start  d-flex justify-content-center align-items-center">
                                {% if content.message_read or content.message_from == user %}
                                <i class="bi bi-envelope-open text-dark fs-1"></i>
                                {% else %}
                                <i class="bi bi-envelope text-dark  fs-1"></i>
                                {% endif %}
                            </div>

                        </div>
                    </a>
                    {% endfor %}
                    {% else %}
                    <p class="lead">Você não possui nenhuma mensagem.</p>
                    {% endif %}
                </div>

            </div>
        </div>



    </div>
</main>

{% endblock content %}

user/templates/login.html
{% extends "global/base.html" %}

{% block content %}
<main>
    <div class="container mt-5">
        <div class="row justify-content-center">

            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success col-8 text-start" role="alert">
                    <p> {{ message }} </p>                    
                </div>
                {% endfor %}                
                
            {% endif %}
            <div class="col-12 col-sm-10 col-md-8  col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="mt-2">Seja bem vindo!</h2>
                        <hr>
                        <p>Entre para continuar utilizando nossos serviços</p>
                        
                        
                        
                        
                        <form action="" method="post">
                            {% csrf_token %}

                            <div class="col-12 form-floating" style="margin-top: 40px;">
                                {{ form.username }}
                                <label for="txtUser">
                                    Usuário
                                </label>

                                <div class="col-12 form-floating mt-3">
                                    {{ form.password }}
                                    <label for="txtPassword">
                                        Senha
                                    </label>
                                </div>
                                {% if form.non_field_errors %}
                                    <div class="col-12 text-danger mb-2"> 
                                        {{form.non_field_errors}}
                                    </div>
                                {% endif %}
                                
                                <div class="col-12 mt-4 text-center mb-4">
                                    <button class="btn btn-lg btn-dark w-100" type="submit">
                                        Entrar
                                    </button>
                                </div>

                                <hr>

                                <div class="col-12 mt-4">
                                    <p>Não possui uma conta? <a
                                            class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
                                            href={% url "user:create" %}>Registar agora</a></p>
                                    <p>Esqueceu sua senha? <a
                                            class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
                                            href="#">Alterar senha</a></p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

user/templates/profile_user.html
{% extends "global/base.html" %}


{% block content %}

<main>
    <div class="container">
        <div class="row mt-5">
            <div class="col-12">
                <h2>Meus Dados</h2>
                <hr>
            </div>
            <div class="col-10 mx-auto">
                <h4>ID MockBank</h4>
                <p class="lead ms-2 opacity-75"> {{ base_user.user_id }}</p>

                <h4>Usuário</h4>
                <p class="lead ms-2 opacity-75"> {{ user.username }}</p>

                <h4>Email</h4>
                <p class="lead ms-2 opacity-75"> {{ user.email }}</p>

            </div>
            <div class="col-10 mx-auto">
                <hr>
                <div class="col-5 float-start">
                    <h4>Nome</h4>
                    <p class="lead ms-2 opacity-75"> {{ user.first_name }} {{ user.last_name }}</p>
                </div>
                <div class="col-5 float-end">
                    <h4>Telefone</h4>
                    <p class="lead ms-2 opacity-75"> {{base_user.user_phone }} </p>
                </div>
            </div>
            <hr>
            <div class="col-12">
                <h2>Dados Financeiros</h2>
                <a href={% url "service:finance_data_update" %} class="btn btn-dark">Acessar</a>
            </div>
            <div class="col-12">
                <hr>
                <p class="fs-5">Olá Sr(a) <strong>{{ user.first_name }}</strong>, caso necessite atualizar seus Dados Pessoais, entre em contato com nossa central de atendimento.</p>
                <p class="fs-5">Atenciosamente, Central de Relacionamento MockBank.</p>
            </div>
        </div>
    </div>

</main>

{% endblock content %}