home/urls.py
from django.urls import path 

from home import views 

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'), 
    path('contact-us/', views.contact_us, name='contact_us'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')), 
    path('', include('user.urls')), 
    path('service/', include('service.urls')), 
]

service/urls.py
from django.urls import path 

from service import views 

app_name = 'service'

urlpatterns = [
    path('transfer/', views.TransferPage.as_view(), name='transfer'), 
    path('extract/', views.ExtractAccountView.as_view(), name='extract'), 
    path('loan-simulate/', views.NotLoggedLoan, name='loan_simulate'), 

    path('finance_data/contains/', views.FinanceDataUserView.as_view(), name='finance_data_content'),
    path('finance_data/update/', views.FinanceDataUserUpdateView.as_view(), name='finance_data_update'), 

    path('loan/', views.LoanView.as_view(), name='loan'),  
    path('verify_loan/', views.loan, name='verify_loan'), 
    path('confirm_loan/', views.ConfirmLoanView.as_view(), name='confirm_loan'), 

    path('deposit/', views.DepositView.as_view(), name='deposit'), 
]

user/urls.py
from django.urls import path 

from user import views 

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),  

    path("home/", views.HomePageView.as_view(), name="home"),

    path('user/create/', views.CreateUser.as_view(), name='create'), 

    path('user/messages/', views.ListMessageUser.as_view(), name='list_messages'), 
    path('user/messages/new/', views.NewMessageView.as_view(), name='create_message'), 
    path('user/messages/<slug:message_id>/', views.MessageDetailView.as_view(), name='detail_message'),

    path('profile/', views.ProfileUser.as_view(), name='profile'), 
    
]

service/forms/deposit_form.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate

import datetime 

from service.models import TransferModel
from user.models import User 

class DepositForm(forms.ModelForm): 
    password = forms.CharField(required=True, label="Senha (A mesma utilizada para login)", label_suffix="", widget=forms.PasswordInput(attrs={
        'class': 'form-control', 
        'id': 'passwordInput', 
    }))

    class Meta: 
        model = TransferModel
        fields = ('value', )
        labels = {
            'value': 'Valor do depósito', 
        }
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
 
        self.user = user 
        self.fields['value'].widget.attrs.update({
            'class': 'form-control', 
            'id': 'valueInput', 
            'min': '0', 
            'max': '999', 
        })

        self.fields['value'].label_suffix=""

    def clean_password(self): 
        password = self.cleaned_data['password']
 
        auth = authenticate(username=self.user.username, password=password)
        
        if auth: 
            return password

        raise ValidationError("Senha incorreta, tente novamente.") 
    
    def save(self, commit=True):
        instance = super().save(commit=False)
        
        user = User.objects.get(owner=self.user)

        instance.sent_by = user
        instance.category = 'deposit'

        user.account_balance += self.cleaned_data['value']
        if user.finance_data.score < 1000: 
            user.finance_data.score += 10

        if commit:
            instance.save()
            user.finance_data.save()
            user.save()

        return instance

service/forms/extract_form.py
from django import forms 

class ExtractForm(forms.Form): 
    FILTER_CHOICES = [
        ('all', 'Todas transações'), 
        ('received', 'Entrada'), 
        ('sent', 'Saída')
    ]
    
    filter_type = forms.ChoiceField(choices=FILTER_CHOICES, widget=forms.Select(attrs={'class': 'form-control form-control-lg mt-0 h-100'}))

service/forms/finance_data_form.py
from django import forms 

from user.models import FinanceDataUser, User 


class FinanceDataForm(forms.ModelForm): 
    EDUCATION_CHOICE = [
        ("1", "Graduação completa"), 
        ("0", "Graduação incompleta"), 
    ]

    EMPLOYED_CHOICE = [
        ("1", "Empregado"), 
        ("0", "Não empregado"), 
    ]

    education = forms.ChoiceField(choices=EDUCATION_CHOICE, label="Educação", required=True, widget=forms.Select(attrs={"class": "form-select", "id": "educacaoInput"}))
    employed = forms.ChoiceField(choices=EMPLOYED_CHOICE, label="Situação empregatícia", required=True, widget=forms.Select(attrs={"class": "form-select", "id": "empregoInput"}))

    class Meta: 
        model = FinanceDataUser 
        fields = ('dependents',  'annual_income', 
                  'residential_assets', 'commercial_assets', 'luxury_assets', 
                  'bank_assets',)
        labels = {
            'dependents': 'Dependentes', 
            'annual_income': 'Renda anual (R$)', 
            'residential_assets': 'Patrimônio residencial', 
            'commercial_assets': 'Patrimônio comercial', 
            'luxury_assets': 'Patrimônio luxo', 
            'bank_assets': 'Patrimônio bancário',  
        }

    def __init__(self, *args, **kwargs): 
        user = kwargs.pop('user', None)

        super(FinanceDataForm, self).__init__(*args, **kwargs)

        self.user = User.objects.get(owner=user)
        
        self.fields['dependents'].widget.attrs.update({
            'class': 'form-control', 
            'id': 'dependentesInput', 
        })
        self.fields['education'].widget.attrs.update({
            'class': 'form-control', 
            'id': 'educacaoInput', 
        })
        self.fields['employed'].widget.attrs.update({
            'class': 'form-control', 
            'id': 'empregoInput', 
        })
        self.fields['annual_income'].widget.attrs.update({
            'class': 'form-control',
            'id': 'rendaInput' 
        })
        self.fields['residential_assets'].widget.attrs.update({
            'class': 'form-control',
            'id': 'residencialInput',  
        })
        self.fields['commercial_assets'].widget.attrs.update({
            'class': 'form-control', 
            'id': 'comercialInput', 
        })
        self.fields['luxury_assets'].widget.attrs.update({
            'class': 'form-control',
            'id': 'luxoInput',  
        })
        self.fields['bank_assets'].widget.attrs.update({
            'class': 'form-control',
            'id': 'bancoInput' 
        })

        self.label_suffix = ''
    
    def save(self, commit=True): 
        instance = super().save(commit=False)
        
        instance.user = self.user 
        instance.employed = int(self.cleaned_data['employed'])
        instance.education = int(self.cleaned_data['education'])

        if commit: 
            instance.save()
        return instance 

service/views.py
from django.shortcuts import render, redirect
from django.contrib import messages 
from django.views.generic.base import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator, classonlymethod
from django.core.paginator import Paginator

from asgiref.sync import sync_to_async
import asyncio 

from . import forms 
from service.services import TransferService, SimulateLoanService, ExtractService, GetFinanceDataService, CreateNewLoanService
from user.services import UserService
from user.models import User 
@method_decorator(login_required(login_url='user:login'), name='dispatch')
class TransferPage(View):
    def get(self, request):
        context = {
            'form': forms.TransferForm(from_user=request.user), 
            'account': UserService.user_balance(self.request.user.id), 
        }

        return render(request, 'transfer_page.html', context)

    def post(self, request):
        form = forms.TransferForm(request.POST, from_user=request.user)

        if form.is_valid(): 
            transfer_to = form.cleaned_data['received_by_username']
            
            data = {
                'sent_user': self.request.user.id, 
                'received_user': transfer_to.owner.id, 
                'value': form.cleaned_data['value'], 
            }
            
            TransferService.update_account_balance(data)

            form.save()

            messages.success(request, f"Você realizou uma transferência para { transfer_to.owner.username }.")
            
            return redirect('user:home')
        
        context = {
            'form': forms.TransferForm(request.POST, from_user=request.user), 
            'account': UserService.user_balance(self.request.user.id), 
        }
        return render(request, 'transfer_page.html', context)

@method_decorator(login_required(login_url='user:login'), name='dispatch')
class ExtractAccountView(View): 
    template_name = 'extract_page.html' 
    form_class = forms.ExtractForm
    
    def get(self, request, *args, **kwargs):
        form = self.form_class(request.GET)

        filter_type = form['filter_type'].value() if form.is_valid() else 'all' 

        user = User.objects.get(owner=request.user)

        queryset = ExtractService.extract_account(filter_type=filter_type, user_id=user.user_id)
        paginator = Paginator(queryset, 8)
        page_number = request.GET.get("page")

        page_obj = paginator.get_page(page_number)
        
        context = {
            'form': form, 
            'page_obj': page_obj, 
        }

        return render(request, self.template_name, context)
    
async def NotLoggedLoan(request): 
    if request.method == 'POST': 
        form = forms.LoanSimulateForm(request.POST)

        if form.is_valid(): 
            context = {
                'response': await SimulateLoanService.simulate_loan_api(request), 
                'name': request.POST.get('name'), 
            }

            return render(request, 'response_not_logged_loan.html', context)
        
        context = {
            'form': form 
        }
        return render(request, 'not_logged_loan.html', context)
    
    context = {
        'form': forms.LoanSimulateForm()
    }

    return render(request, 'not_logged_loan.html', context)
@method_decorator(login_required(login_url='user:login'), name='dispatch')
class FinanceDataUserView(View): 
    def get(self, request): 
        user = User.objects.get(owner=request.user)

        if user.finance_data.active is False: 
            context = {
                'form': forms.FinanceDataForm(user=request.user, instance=user.finance_data),
                'subtitle': 'Primeiro, vamos registrar alguns de seus dados financeiros.', 
                'button': 'Enviar'
            }
            return render(request, 'finance_data_register.html', context)
        
        return redirect('service:loan')

    def post(self, request): 
        user = User.objects.get(owner=request.user)
        form = forms.FinanceDataForm(request.POST, user=request.user, instance=user.finance_data) 

        if form.is_valid(): 
            form = form.save(commit=False)
            
            form.active = True 
            form.save()
            messages.success(request, 'Suas informações foram registradas com sucesso!')

            return redirect('service:loan')
        context = { 
            'form': form,
            'subtitle': 'Primeiro, vamos registrar alguns de seus dados financeiros.', 
            'button': 'Enviar' 
        }

        return render(request, 'finance_data_register.html', context)
    
@method_decorator(login_required(login_url='user:login'), name='dispatch')
class FinanceDataUserUpdateView(View): 
    def get(self, request): 
        user = User.objects.get(owner=request.user)

        context = {
            'form': forms.FinanceDataForm(user=request.user, instance=user.finance_data),
            'subtitle': 'Atualizar dados', 
            'button': 'Salvar'
        }
        return render(request, 'finance_data_register.html', context)

    def post(self, request): 
        user = User.objects.get(owner=request.user)
        form = forms.FinanceDataForm(request.POST, user=request.user, instance=user.finance_data) 

        if form.is_valid(): 
            form.save()
            messages.success(request, 'Suas informações foram atualizadas com sucesso!')

            return redirect('user:home')
        context = { 
            'form': form,
            'subtitle': 'Atualizar dados', 
            'button': 'Salvar'
        }

        return render(request, 'finance_data_register.html', context)
    
@method_decorator(login_required(login_url='user:login'), name='dispatch')
class LoanView(View): 
    def get(self, request): 
        context = {
            'form': forms.LoanForm()
        }

        return render(request, 'loan.html', context)


@sync_to_async
def get_user_from_request(request) -> User | None:
    return request.user if bool(request.user) else None

@sync_to_async
def get_data(*args, **kwargs) -> dict | None: 
    data = GetFinanceDataService.get_finance_data(user=kwargs.get('user'), value=kwargs.get('value'), payment=kwargs.get('payment'))
    
    return data if data else None 


async def loan(request):
    user = await get_user_from_request(request) 
    if user: 
        form = forms.LoanForm(request.POST)

        if form.is_valid(): 
            data = await get_data(user=user, value=request.POST.get('value'), payment=request.POST.get('payment'))

            response = await SimulateLoanService.simulate_loan_api(data=data)
            
            if response is True: 
                request.session['data'] = {
                    'value': request.POST.get('value'), 
                    'payment': request.POST.get('payment'), 
                }

                return redirect('service:confirm_loan')

            else: 
                messages.error(request, "Infelizmente não podemos aprovar o valor solicitado neste momento.")

                return render(request, 'loan.html', {'form': form})            
        
        return render(request, 'loan.html', {'form': form})
    
    return redirect('user:login')

@method_decorator(login_required(login_url='user:login'), name='dispatch')
class ConfirmLoanView(View): 
    def get(self, request): 
        form = forms.ConfirmLoanForm(user=request.user)

        context = {
            'value': request.session['data'].get('value'), 
            'payment': request.session['data'].get('payment'), 
            'form': form, 
        }

        return render(request, 'confirm_loan.html', context)
    
    def post(self, request): 
        form = forms.ConfirmLoanForm(request.POST, user=request.user)

        if form.is_valid(): 
            value = request.session['data'].get('value')
            payment = request.session['data'].get('payment')

            response = CreateNewLoanService.create_loan(user=request.user, value=value, payment=payment)

            if response is not False: 
                messages.success(request, "Seu empréstimo foi realizado com sucesso! Em breve, o valor será debitado na sua conta.")

                del request.session['data']

                return redirect('user:home')
            
            messages.error(request, "A operação pode ser realizada apenas uma vez por dia.")
            
            return redirect('service:loan')
        
        context = {
            'value': request.session['data'].get('value'), 
            'payment': request.session['data'].get('payment'), 
            'form': form, 
        }

        return render(request, 'confirm_loan.html', context)


@method_decorator(login_required(login_url='user:login'), name='dispatch')
class DepositView(View): 
    
    def get(self, request): 
        context = {
            'form': forms.DepositForm(user=request.user)
        }
        return render(request, 'deposit.html', context)
    
    def post(self, request): 
        form = forms.DepositForm(request.POST, user=request.user)

        if form.is_valid(): 
            if TransferService.verify_deposity_on_day(request.user): 
                form.save()
                messages.success(request, 'Depósito realizado com sucesso!')

                return redirect('user:home')

            messages.error(request, "Neste momento, a operação de depósito pode ser realizada apenas uma vez ao dia.")
            
            return redirect('user:home')
            
        return render(request, 'deposit.html', {'form': form})

service/templates/confirm_loan.html
{% extends "global/base.html" %}

{% block content %}

<main>
    <div class="container mt-5">
        <h2>Finalizar contratação de empréstimo MockBank </h2>
        <hr>
        <p class="lead">Ótimas notícias Sr(a) {{ user.first_name }}, seu empréstimo no valor de R${{value}} com
            pagamento em {{payment}} vezes foi aprovado!</p>
        <p class="lead">Para confirmar, digite sua senha</p>
        <div class="row justify-content-center mt-4">
            <div class="col-12 col-md-10 col-lg-8">
                <form action="" method="post">
                    {% csrf_token %}

                    <p>{{ form.password.errors }}</p>  
                    <div class="form-floating mb-3">
                        {{ form.password }}
                        <label for="passwordInput"> {{ form.password.label }}</label>
                    </div>
                    

                    <button class="btn btn-dark" type="submit">Confirmar empréstimo</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

service/templates/deposit.html
{% extends "global/base.html" %}

{% block content %}
<main>
    <div class="container mt-5">
        <h2>Realizar depósito Mockbank </h2>
        <hr>
        <div class="row justify-content-center mt-4">
            <div class="col-12 col-md-10 col-lg-8">
                <form action="" method="post">
                    {% csrf_token %}

                    {{ form.non_field_errors }}
                    
                    <p> {{ form.value.errors }}</p>
                    <div class="form-floating mb-3">
                        {{ form.value }}
                        <label for="passwordInput"> {{ form.value.label }}</label>
                    </div>
                    <p> {{ form.password.errors }}</p>
                    <div class="form-floating mb-3">
                        {{ form.password }}
                        <label for="passwordInput"> {{ form.password.label }}</label>
                    </div>
                    <button class="btn btn-dark" type="submit">Realizar depósito</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

service/templates/extract_page.html
{% extends "global/base.html" %}
{% load humanize %}

{% block content %}
<main>
    <div class="container mt-5 mb-5">
        <div class="col-12 col-lg-10 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h3 class="mt-2">Extrato da conta</h3>
                    <hr class="mb-4">
                    
                    
                    <form method="get" action="" id="extract-form">
                        <p class="lead">Filtrar</p>
                        {% csrf_token %}
                        {{ form.filter_type }}
                    </form>

                    <div class="col-12">
                        <div class="row mx-auto mt-3">
                            {% if page_obj %}
                            {% for item in page_obj %}
                                <a href="#" class="mb-2" style="text-decoration: none;">
                                    <div class="container border rounded border-dark text-dark">
                                        <div class="row">
                                            <div class="col-8 col-sm-9 mt-1 ">
                                                <p class="opacity-75">{{ item.transfer_id }}</p>

                                                {% if item.category == 'deposit' %}
                                                <p>Entrada - <strong>Depósito</strong> em {{ item.created_at }}</p>
                                                {% elif item.sent_by.owner == user %}
                                                <p>Saída - transferência para <strong>{{ item.received_by.owner }}</strong> em {{ item.created_at }}</p>
                                                {% else %}
                                                <p>Entrada - <strong>{{ item.sent_by.owner }}</strong> em {{ item.created_at }}</p>
                                                {% endif %}
                                            </div>
                                            <div class="col-4 col-sm-3 text-end my-auto">
                                                {% if item.category == 'deposit' or item.received_by.owner == user %}
                                                <p class="text-success my-auto lead"> R$ {{item.value}} </p> 
                                                {% else %}
                                                <p class="text-danger my-auto lead"> R$ {{item.value}} </p> 
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            
                            {% endfor %}
                            {% else %}
                            <p class="lead">
                                Você não possui histórico de transações.
                            </p>
                            {% endif %}
                        </div>
                    </div>
                    
                    <div class="col-12 text-center mt-3">
                        <nav>
                            <ul class="pagination justify-content-center">
                                {% if page_obj.has_previous %}
                                <li class="page-item ">  
                                    <a class="page-link" href="?page=1{% if form.filter_type.value %}&filter_type={{ form.filter_type.value }}{% endif %}">Anterior</a>
                                </li>
                                {% else %}
                                <li class="page-item disabled">  
                                    <a href="#" class="page-link">Anterior</a>
                                </li>
                                {% endif %}
                                
                                 <span class="mt-2 mx-3">
                                    Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
                                 </span>   
                                
                                    
                                {% if page_obj.has_next %}
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if form.filter_type.value %}&filter_type={{ form.filter_type.value }}{% endif %}">Próxima</a>
                                
                                {% else %}
                                <a class="page-link disabled" href="#">Próxima</a>
                                {% endif %}
                            </ul>
                          </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<script>
document.getElementById('id_filter_type').addEventListener('change', function() {
    var filterValue = this.value;
    var form = document.getElementById('extract-form');
    form.action = '?' + 'filter_type=' + filterValue;
    form.submit();
});
</script>
{% endblock content %}

service/templates/loan.html
{% extends "global/base.html" %}

{% block content %}
<main>
    <div class="container mt-5">
        {% if messages %}
        {% for message in messages %}
        <div class= {% if message.tags == 'error' %}"alert alert-danger col-8 text-start mt-5"{% else %} "alert alert-success col-8 text-start mt-5"{% endif %}role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        <h2>Realizar empréstimo Mockbank </h2>
        <hr>
        <p class="lead">Inicialmente, vamos consultar seus dados e analisar a proposta. Fique tranquilo, é rápido, simples.</p>
        <div class="row justify-content-center mt-4">
            <div class="col-12 col-md-10 col-lg-8">
                <form action= {% url "service:verify_loan" %} method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <button class="btn btn-dark" type="submit">Realizar empréstimo</button>
                </form>

            </div>
        </div>
        
    </div>
</main>
{% endblock content %}

service/templates/response_loan.html
{% extends "global/base.html" %}

{% block content %}

{% if response == True %}
    <main>
        <div class="container mt-4 mb-4 mt-md-5">
            <div class="row">
                <div class="col-12 mb-3">
                    <h3>Ótima notícia Sr(a) <strong>{{ name }}</strong>, seu empréstimo pode ser aprovado no MockBank!</h3>
                </div>
                <hr>

                <div class="col-12 col-md-8 mt-3">
                    <p>Caro Sr(a) <strong>{{ name }}</strong>,</p>
                    <p>Ficamos felizes em informar que o seu empréstimo pode ser aprovado imediatamente no MockBank.</p>

                    <p>Então... Vamos criar uma conta MockBank?</p>
                    <p>É rápido, simples e seguro!</p>

                    <a href={% url "user:create" %} class="btn btn-dark mt-3">Criar minha conta Mockbank</a>
                </div>
            </div>
        </div>
    </main>
{% else %}
    {% if response == False %}
    <main>
        <div class="container mt-4 mb-4 mt-md-5">
            <div class="row">
                <div class="col-12 mb-3">
                    <h3>Sr(a) <strong>{{ name }}</strong>, infelizmente seu empréstimo não pode ser aprovado no MockBank neste
                        momento.</h3>
                </div>
                <hr>

                <div class="col-12 col-md-8 mt-3">
                    <p>Caro Sr(a) <strong>{{ name }}</strong>,</p>
                    <p>Neste momento, não podemos aprovar sua solicitação de empréstimo.</p>

                    <p>
                        No entanto, sua solicitação pode ser reavaliada conforme movimentação e uso da conta MockBank.
                    </p>

                    <p>Então... Vamos criar uma conta MockBank?</p>
                    <p>É rápido, simples e seguro!</p>

                    <a href={% url "user:create" %} class="btn btn-dark mt-3">Criar minha conta Mockbank</a>
                </div>
            </div>
    </main>
    {% else %}
        <main>
            <div class="container mt-4 mb-4 mt-md-5">
                <div class="row">
                    <div class="col-12 mb-3">
                        <h3>Infelizmente não foi possível atender sua solicitação neste momento.</h3>
                    </div>
                    <hr>
        
                    <div class="col-12 col-md-8 mt-3">
                        <p>Estamos trabalhando para corrigir este problema, tente novamente mais tarde.</p>
                        <p>Central de Relacionamento MockBank.</p>
        
                    </div>
                </div>
            </div>
        </main>
    {% endif %}
{% endif %}
{% endblock content %}

service/templates/response_not_logged_loan.html
{% extends "global/base.html" %}

{% block content %}

{% if response == True %}
    <main>
        <div class="container mt-4 mb-4 mt-md-5">
            <div class="row">
                <div class="col-12 mb-3">
                    <h3>Ótima notícia Sr(a) <strong>{{ name }}</strong>, seu empréstimo pode ser aprovado no MockBank!</h3>
                </div>
                <hr>

                <div class="col-12 col-md-8 mt-3">
                    <p>Caro Sr(a) <strong>{{ name }}</strong>,</p>
                    <p>Ficamos felizes em informar que o seu empréstimo pode ser aprovado imediatamente no MockBank.</p>

                    <p>Então... Vamos criar uma conta MockBank?</p>
                    <p>É rápido, simples e seguro!</p>

                    <a href={% url "user:create" %} class="btn btn-dark mt-3">Criar minha conta Mockbank</a>
                </div>
            </div>
        </div>
    </main>
{% else %}
    {% if response == False %}
    <main>
        <div class="container mt-4 mb-4 mt-md-5">
            <div class="row">
                <div class="col-12 mb-3">
                    <h3>Sr(a) <strong>{{ name }}</strong>, infelizmente seu empréstimo não pode ser aprovado no MockBank neste
                        momento.</h3>
                </div>
                <hr>

                <div class="col-12 col-md-8 mt-3">
                    <p>Caro Sr(a) <strong>{{ name }}</strong>,</p>
                    <p>Neste momento, não podemos aprovar sua solicitação de empréstimo.</p>

                    <p>
                        No entanto, sua solicitação pode ser reavaliada conforme movimentação e uso da conta MockBank.
                    </p>

                    <p>Então... Vamos criar uma conta MockBank?</p>
                    <p>É rápido, simples e seguro!</p>

                    <a href={% url "user:create" %} class="btn btn-dark mt-3">Criar minha conta Mockbank</a>
                </div>
            </div>
    </main>
    {% else %}
        <main>
            <div class="container mt-4 mb-4 mt-md-5">
                <div class="row">
                    <div class="col-12 mb-3">
                        <h3>Infelizmente não foi possível atender sua solicitação neste momento.</h3>
                    </div>
                    <hr>
        
                    <div class="col-12 col-md-8 mt-3">
                        <p>Estamos trabalhando para corrigir este problema, tente novamente mais tarde.</p>
                        <p>Central de Relacionamento MockBank.</p>
        
                    </div>
                </div>
            </div>
        </main>
    {% endif %}
{% endif %}
{% endblock content %}